### ISSUE TITLE
goudmp无法dump struct

### ISSUE THREAD

**Issue by Ovear** [liudng/godump#4]
在如下代码中，godump会返回
p := person{firstName: "a", lastName: "n"}
godump.Dump(p)

(main.person)
  firstName(string) ""
  lastName(string) ""

而使用fmt.Printf("%+v\n", p)
可以正常返回
{firstName:a lastName:n}

**Comment by liudng** [comment]
godump只能访问可导出方法， 所以只能dump出大写母开头的属性或方法。

**Comment by Ovear** [comment]
好的谢谢0v0
